#!/bin/bash

# for update *.deb packages (do not delete it, for reference)
#yes N | sudo dpkg -i *.deb

sudo cp auto_update /etc/croissants/conf.d/
sudo chmod +x /etc/croissants/conf.d/auto_update

sudo cp nsm_rules_update /usr/bin/
sudo chmod +x /usr/bin/nsm_rules_update

sudo nsm_rules_update
