#!/bin/bash
# Author   : Samiux (https://www.infosec-ninjas.com)
# Date     : JUL 20, 2017
# License  : GPLv3 (Open Source)

cd /tmp
git clone https://github.com/StamusNetworks/stamus-luajit-scripts.git
sudo cp stamus-luajit-scripts/*.lua /etc/suricata/rules/
sudo cp /etc/suricata/rules/*.lua /var/lib/suricata/rules/

# set up 3rd party rules
# sslblacklist fingerprint
#cd /tmp
#wget https://sslbl.abuse.ch/blacklist/sslblacklist.rules
#if [ -s sslblacklist.rules ]
#then
#	sudo cat sslblacklist.rules > /etc/suricata/rules/local-sslblacklist.rules
#	sudo echo >> /etc/suricata/rules/local-sslblacklist.rules
#	sudo sed -i -e 's/alert/reject/g' /etc/suricata/rules/local-sslblacklist.rules
#	sudo sed -i -e 's/tls_fingerprint/tls.fingerprint/g' /etc/suricata/rules/local-sslblacklist.rules
#fi

# merge local-sslblacklist.rules to suri-local.rules
#sudo cat /etc/suricata/rules/local-sslblacklist.rules > /etc/suricata/rules/suri-local.rules
#sudo echo >> /etc/suricata/rules/suri-local.rules

# for suricata-update
#sudo cp /etc/suricata/rules/suri-local.rules /var/lib/suricata/rules/

# set up 3rd party ip blocking list
#
# talosintel
#
cd /tmp
wget http://talosintel.com/feeds/ip-filter.blf -O /tmp/ip-filter.blf
if [ -s /tmp/ip-filter.blf ]
then
	cat /tmp/ip-filter.blf | sort -u | sed -e 's/$/,1,10/' > /etc/suricata/rules/iprep/ip-filter.blacklist
	# for suricata-update
#	sudo cp /etc/suricata/rules/iprep/ip-filter.blacklist /var/lib/suricata/rules/iprep/
fi

#
# openbl.org (It has been shutting down on May 2017)
#
#cd /tmp
#wget https://www.openbl.org/lists/base_30days.txt -O /tmp/openbl.txt
#if [ -s /tmp/openbl.txt ]
#then
#	grep -v "#" /tmp/openbl.txt | sort -u | sed -e 's/$/,1,10/' > /etc/suricata/rules/iprep/openbl.blacklist
#fi

#
# zeustracker.abuse.ch
#
cd /tmp
wget https://zeustracker.abuse.ch/blocklist.php?download=badips -O /tmp/zeustracker.txt
if [ -s /tmp/zeustracker.txt ]
then
	grep -v "#" /tmp/zeustracker.txt | grep -v " " /tmp/zeustracker.txt | grep -v "" /tmp/zeustracker.txt | sort -u | sed -e 's/$/,1,10/' > /etc/suricata/rules/iprep/zeustracker.blacklist
	# for suricata-update
#	sudo cp /etc/suricata/rules/iprep/zeustracker.blacklist /var/lib/suricata/rules/iprep/
fi

#
# blocklist.de
#
cd /tmp
wget https://lists.blocklist.de/lists/dnsbl/allinone.list -O /tmp/allinone.list
if [ -s /tmp/allinone.list ]
then
	sed 's/:.*//' /tmp/allinone.list | sed -e '/^\s*$/d' | sort -u | sed -e 's/$/,1,10/' > /etc/suricata/rules/iprep/blocklist.de.blacklist
	# for suricata-update
#	sudo cp /etc/suricata/rules/iprep/blocklist.de.blacklist /var/lib/suricata/rules/iprep/
fi

#
# abuse.ch Aggressive SSL
#
#cd /tmp
#wget https://sslbl.abuse.ch/blacklist/sslipblacklist_aggressive.csv -O /tmp/sslipblacklist_aggressive.csv
#if [ -s /tmp/sslipblacklist_aggressive.csv ]
#then
#	grep -v "#" /tmp/sslipblacklist_aggressive.csv | cut -d "," -f 1 | sort -u | sed -e 's/$/,1,10/' > /etc/suricata/rules/iprep/sslip.blacklist
#	# for suricata-update
#	sudo cp /etc/suricata/rules/iprep/sslip.blacklist /var/lib/suricata/rules/iprep/
#fi

#
# IPBLC Server IP Blacklist
#
cd /tmp
wget http://www.ip-finder.me/ip-full-list/ -O /tmp/ip-finder.me.html
if [ -s /tmp/ip-finder.me.html ]
then
	grep -P -o '(?<=/)[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}(?=/)' /tmp/ip-finder.me.html | sort -u | sed -e 's/$/,1,10/' > /etc/suricata/rules/iprep/ip-finder.blacklist
	# for suricata-update
#	sudo cp /suricata/rules/iprep/ip-finder.blacklist /var/lib/suricata/rules/iprep/
fi

#
# denyhosts
#
# Ubuntu has no this package anymore (last check in Nov, 2015).  If denyhosts is installed, you can uncomment it and edit /etc/suricata/suricata.yaml accordingly.
#[ -f /var/lib/denyhosts/sync-received ] && cat /var/lib/denyhosts/sync-received | cut -d ":" -f 1 | sort -u | sed -e 's/$/,1,10/' > /etc/suricata/rules/iprep/denyhosts.blacklist
# or use the following source
#cd /tmp
#if [ -s /tmp/denyhosts.bitwash.blacklist ]
#then
#	sudo cp /tmp/denyhosts.bitwash.blacklist /etc/suricata/rules/iprep/denyhosts.bitwash.blacklist
#fi

#cd /tmp
#wget http://rbl.bitwash.org/iprep/denyhosts.sync.blacklist -O /tmp/denyhosts.sync.blacklist
#if [ -s /tmp/denyhosts.sync.blacklist ]
#then
#	sudo cp /tmp/denyhosts.sync.blacklist /etc/suricata/rules/iprep/denyhosts.sync.blacklist
#	# for suricata-update
#	sudo cp /etc/suricata/rules/iprep/denyhosts.sync.blacklist /var/lib/suricata/rules/iprep/
#fi

#
# TOR Exit Nodes
#
cd /tmp
#wget https://torstatus.blutmagie.de/ip_list_exit.php/Tor_ip_list_EXIT.csv
#if [ -s /tmp/Tor_ip_list_EXIT.csv ]
#then
#	cat /tmp/Tor_ip_list_EXIT.csv | sort -u | sed -e 's/$/,2,10/' > /etc/suricata/rules/iprep/tor.torexitnode
#	# for suricata-update
##	sudo cp /etc/suricata/rules/iprep/tor.torexitnode /var/lib/suricata/rules/iprep/
#fi
wget https://check.torproject.org/cgi-bin/TorBulkExitList.py?ip=1.1.1.1 -O TorBulkExitList
if [ -s /tmp/TorBulkExitList ]
then
	sed -i "/^#/d" /tmp/TorBulkExitList
	cat /tmp/TorBulkExitList | sort -u | sed -e 's/$/,2,10/' > /etc/suricata/rules/iprep/tor.torexitnode
fi

#
# croissants2.rules
#
cd /tmp
wget https://github.com/samiux/update-croissants/raw/master/rules/croissants2.rules -O /tmp/croissants2.rules
if [ -s /tmp/croissants2.rules ]
then
	sudo cp /tmp/croissants2.rules /etc/suricata/rules/croissants2.rules
	# for suricata-update
	sudo cp /etc/suricata/rules/croissants2.rules /var/lib/suricata/rules/

fi

#
# croissants.rules
#
cd /tmp
wget https://github.com/samiux/update-croissants/raw/master/rules/croissants.rules -O /tmp/croissants.rules
if [ -s /tmp/croissants.rules ]
then
	sudo cp /tmp/croissants.rules /etc/suricata/rules/croissants.rules
	# for suricata-update
	sudo cp /etc/suricata/rules/croissants.rules /var/lib/suricata/rules/

fi

#
# PhishTank.com Bad Urls
#
cd /tmp
wget http://data.phishtank.com/data/online-valid.csv.bz2
if [ -s /tmp/online-valid.csv.bz2 ]
then
	bzip2 -dk /tmp/online-valid.csv.bz2
	sed '1d' /tmp/online-valid.csv | cut -d "," -f 2 | sed '/^"/d' | sort -u > /tmp/phishtank.url
	sed -i -e '/http:\/\/www\.baidu\.com.*/d' /tmp/phishtank.url
	sudo cp /tmp/phishtank.url /etc/suricata/rules/
	# for suricata-update
	sudo cp /etc/suricata/rules/phishtank.url /var/lib/suricata/rules/
fi

#
# cryptXXX ransomware
#
cd /tmp
wget https://github.com/samiux/update-croissants/raw/master/rules/cryptxxx_md5 -O /tmp/cryptxxx_md5
if [ -s /tmp/cryptxxx_md5 ]
then
	sudo cp /tmp/cryptxxx_md5 /etc/suricata/rules/
	# for suricata-updaate
	sudo cp /etc/suricata/rules/cryptxxx_md5 /var/lib/suricata/rules/
fi

cd /tmp
wget https://github.com/samiux/update-croissants/raw/master/rules/cryptxxx.blacklist -O /tmp/cryptxxx.blacklist
if [ -s /tmp/cryptxxx.blacklist ]
then
	sudo cp /tmp/cryptxxx.blacklist /etc/suricata/rules/iprep/
	# for suricata-update
#	sudo cp /etc/suricata/rules/iprep/cryptxxx.blacklist /var/lib/suricata/rules/iprep/
fi

cd /tmp
wget https://github.com/samiux/update-croissants/raw/master/rules/cryptxxx.url -O /tmp/cryptxxx.url
if [ -s /tmp/cryptxxx.url ]
then
	sudo cp /tmp/cryptxxx.url /etc/suricata/rules/
	# for suricata-update
	sudo cp /etc/suricata/rules/cryptxxx.url /var/lib/suricata/rules/
fi

#
# WannaCry ransomware sinkhole
#
#cd /tmp
#wget https://www.infosec-ninjas.com/files/rules/wannacry.url -O /tmp/wannacry.url
#if [ -s /tmp/wannacry.url ]
#then
#  sudo cp /tmp/wannacry.url /etc/suricata/rules/
#  # for suricata-update
#  sudo cp /etc/suricata/rules/wannacry.url /var/lib/suricata/rules/
#fi

#
# xss_sqli pattern
#
cd /tmp
wget https://github.com/samiux/update-croissants/raw/master/rules/xss_sqli_pattern.url -O xss_sqli_pattern.url
if [ -s /tmp/xss_sqli_pattern.url ]
then
	sudo cp /tmp/xss_sqli_pattern.url /etc/suricata/rules/
	# for suricata-update
	sudo cp /etc/suricata/rules/xss_sqli_pattern.url /var/lib/suricata/rules/
fi

#
# feodotracker trojan tracker
# https://feodotracker.abuse.ch/blocklist/
#
#cd /tmp
#wget https://feodotracker.abuse.ch/blocklist/?download=suricata -O /tmp/temp.rules
#if [ -s /tmp/temp.rules ]
#then
#  grep -v "#" /tmp/temp.rules | sed -e 's/alert http/drop http/' > /etc/suricata/rules/feodotracker.rules
#  # for suricata-update
#  sudo cp /etc/suricata/rules/feodotracker.rules /var/lib/suricata/rules/
#fi

#
# ransomware tracker
#
cd /tmp
wget http://ransomwaretracker.abuse.ch/downloads/RW_DOMBL.txt -O /tmp/RW_DOMBL.txt
if [ -s /tmp/RW_DOMBL.txt ]
then
	grep -v "#" /tmp/RW_DOMBL.txt > /etc/suricata/rules/ransomwaretracker.url
fi

cd /tmp
wget http://ransomwaretracker.abuse.ch/downloads/RW_URLBL.txt -O /tmp/RW_URLBL.txt
if [ -s /tmp/RW_URLBL.txt ]
then
	grep -v "#" /tmp/RW_URLBL.txt >> /etc/suricata/rules/ransomwaretracker.url
	# for suricata-update
	sudo cp /etc/suricata/rules/ransomwaretracker.url /var/lib/suricata/rules/
fi

cd /tmp
wget http://ransomwaretracker.abuse.ch/downloads/RW_IPBL.txt -O /tmp/RW_IPBL.txt
if [ -s /tmp/RW_IPBL.txt ]
then
	grep -v "#" RW_IPBL.txt | sort -u | sed -e 's/$/,1,10/' > /etc/suricata/rules/iprep/ransomwaretracker.blacklist
	# for suricata-update
#	sudo cp /etc/suricata/rules/iprep/ransomwaretracker.blacklist /var/lib/suricata/rules/iprep/
fi

#
# various malware sha1 and sha256 checksum
#
cd /tmp
wget https://github.com/samiux/update-croissants/raw/master/rules/malware_sha1 -O /tmp/malware_sha1
if [ -s /tmp/malware_sha1 ]
then
  sudo cp /tmp/malware_sha1 /etc/suricata/rules/
  # for suricata-update
  sudo cp /etc/suricata/rules/malware_sha1 /var/lib/suricata/rules/
fi

cd /tmp
wget https://github.com/samiux/update-croissants/raw/master/rules/malware_sha256 -O /tmp/malware_sha256
if [ -s /tmp/malware_sha256 ]
then
  sudo cp /tmp/malware_sha256 /etc/suricata/rules/
  # for suricata-update
  sudo cp /etc/suricata/rules/malware_sha256 /var/lib/suricata/rules/
fi

#
# PT Open Suricata Rules
#
cd /tmp
wget https://github.com/ptresearch/AttackDetection/raw/master/pt.rules.tar.gz
if [ -s /tmp/pt.rules.tar.gz ]
then
	tar -xvzf /tmp/pt.rules.tar.gz
	cd /tmp/rules
	sudo sed -i -e 's/^alert /drop /g' /tmp/rules/pt-rules.rules
	# delete OpenSSL DoS
	# it causing trouble to Qualsys server certificate checking
	sudo sed -i -e '/sid\: 10000131\;/d' /tmp/rules/pt-rules.rules
	# delete SVN/Git Remote Code Execution throught malicious ssh:// url
	# it causing trouble to openvas signauture update (geeenbone-scapdata-rsync)
	sudo sed -i -e '/sid\: 10001756\;/d' /tmp/rules/pt-rules.rules
	sudo cp /tmp/rules/pt-rules.rules /etc/suricata/rules/
	# for suricata-update
	sudo cp /etc/suricata/rules/pt-rules.rules /var/lib/suricata/rules/
fi

#
# Metasploit Payloads rules
# https://github.com/dgroenewegen/MetaSnort
#
#cd /tmp
#wget https://www.infosec-ninjas.com/files/rules/metasploit-payloads.rules -O /tmp/metasploit-payloads.rules
#if [ -s /tmp/metasploit-payloads.rules ]
#then
#	sudo cp /tmp/metasploit-payloads.rules /etc/suricata/rules/
#	# for suricata-update
#	sudo cp /etc/suricata/rules/metasploit-payloads.rules /var/lib/suricata/rules/
#fi

cd /tmp

#
#SSL Certificate Blacklist
#
# suricata ssl certificate ruleset
wget https://sslbl.abuse.ch/blacklist/sslblacklist_tls_cert.tar.gz

if [ -s /tmp/sslblacklist_tls_cert.tar.gz ]
then
        # extract tar.gz files
        tar -xvzf sslblacklist_tls_cert.tar.gz
        # copy the extracted files to suricata folder
	sudo sed -i -e 's/alert/reject/g' sslblacklist_tls_cert.rules
        sudo cp sslblacklist_tls_cert.rules /etc/suricata/rules/
        sudo cp sslblacklist_tls_cert.rules /var/lib/suricata/rules
fi

# suricata botnet c2 ip ruleset
wget https://sslbl.abuse.ch/blacklist/sslipblacklist.tar.gz

if [ -s /tmp/sslipblacklist.tar.gz ]
then
        # extract tar.gz files
        tar -xvzf sslipblacklist.tar.gz
        # copy the extracted files to suricata folder
	sudo sed -i -e 's/alert/reject/g' sslipblacklist.rules
        sudo cp sslipblacklist.rules /etc/suricata/rules/
        sudo cp sslipblacklist.rules /var/lib/suricata/rules
fi

# suricata ja3 fingerprint ruleset
wget https://sslbl.abuse.ch/blacklist/ja3_fingerprints.tar.gz

if [ -s /tmp/ja3_fingerprints.tar.gz ]
then
        # extract tar.gz files
        tar -xvzf ja3_fingerprints.tar.gz
        # copy the extracted files to suricata folder
	sudo sed -i -e 's/alert/reject/g' ja3_fingerprints.rules
        sudo cp ja3_fingerprints.rules /etc/suricata/rules/
        sudo cp ja3_fingerprints.rules /var/lib/suricata/rules
fi

# cleaning up
sudo rm -R stamus-luajit-scripts
sudo rm /tmp/*.blf
sudo rm /tmp/*.txt
sudo rm /tmp/*.list
sudo rm /tmp/*.csv
sudo rm /tmp/*.html
sudo rm /tmp/*.blacklist
sudo rm /tmp/*.rules*
sudo rm /tmp/*.tar.gz*
sudo rm /tmp/*.bz2
sudo rm /tmp/*.url
sudo rm /tmp/crypt*
sudo rm /tmp/malware*
sudo rm -R /tmp/rules/
cd ~

# loading rules
#sudo idstools-rulecat @/etc/idstools/rulecat.conf
#sudo suricata-update --reload-command='sudo kill -USR2 $(pidof suricata)'
sudo suricata-update

sudo kill -USR2 $(pidof suricata)
#sudo rm /var/tmp/idstools-rulecat/*.tar.gz*

# workaround to fix minor bug of suricata for memory leaking on every reload (-USR2)
sudo sync; sudo sh -c 'echo 3 >/proc/sys/vm/drop_caches'
